name: Docker Build and Push

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make .env.production
        run: |
          touch ./.env.production
          echo "${{ secrets.ENV_PROD }}" > ./.env.production
        shell: bash

      - name: Login to DockerHub
        if: contains(github.ref, 'develop')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        if: contains(github.ref, 'develop')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:${{ secrets.TAG }}

      - name: Deploy IAM Access
        if: contains(github.ref, 'develop')
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_IAM_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.REGION }}

      - name: Code Deploy
        if: contains(github.ref, 'develop')
        run: aws deploy create-deployment --application-name ${{ secrets.DEPLOY_APPLICATION_NAME }} --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name ${{ secrets.DEPLOY_GROUP }} --s3-location bucket=${{ secrets.DEPLOY_S3_BUCKET }},key=${{ secrets.DEPLOY_S3_KEY }},bundleType=zip