name: Docker Build and Push

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make .env.production
        run: |
          touch ./.env.production
          echo "${{ secrets.ENV_PROD }}" > ./.env.production
        shell: bash

      - name: Login to DockerHub
        if: contains(github.ref, 'develop')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        if: contains(github.ref, 'develop')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:${{ secrets.TAG }}